import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createLearningSession } from '../src/learning.js';
import { collectAnswerRecords, collectFieldDescriptors, applyDecisions, planDeterministicFill } from '../src/form-engine.js';
import { mergeLearnedAnswers } from '../src/core.js';
import { mergeAnswerRecords } from '../src/datasource.js';

test('legacy duplicate unscoped answers retain every alternative during migration', () => {
  const merged = mergeAnswerRecords([
    { key: 'company', answer: 'First employer', updatedAt: '2025-01-01T00:00:00Z' },
    { key: 'company', answer: 'Second employer', updatedAt: '2026-01-01T00:00:00Z' },
  ]);
  assert.equal(merged[0].answer, 'Second employer');
  assert.deepEqual(merged[0].alternatives, ['First employer']);
});

test('captures user option clicks that do not dispatch native input events', async () => {
  const dom = new JSDOM('<main><button role="combobox" aria-label="City" aria-controls="cities">Select one</button><div role="listbox" id="cities"><div role="option">London</div></div></main>');
  const document = dom.window.document;
  collectFieldDescriptors(document);
  const sent = [];
  const session = createLearningSession(document, { capture: () => collectAnswerRecords(document), send: async (message) => { sent.push(message); return { ok: true }; } });
  session.activate('run');
  document.querySelector('[role="option"]').addEventListener('click', () => { document.querySelector('button').textContent = 'London'; });
  document.querySelector('[role="option"]').click();
  await session.flush();
  assert.equal(sent[0].records[0].answer, 'London');
  assert.equal(sent[0].records[0].userEdited, true);
  session.dispose();
  dom.window.close();
});

test('learning activates explicitly, debounces edits, and flushes before leaving', async () => {
  const dom = new JSDOM('<label>Email<input id="email" type="email"></label>', { url: 'https://example.com/apply' });
  const document = dom.window.document;
  const sent = [];
  collectFieldDescriptors(document);
  const session = createLearningSession(document, { capture: () => collectAnswerRecords(document), send: async (message) => { sent.push(message); return { ok: true }; }, delayMs: 10 });
  const input = document.querySelector('input');
  input.value = 'initial@example.com';
  input.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
  await session.flush();
  assert.equal(sent.length, 0);
  session.activate('run-1');
  input.value = 'edited@example.com';
  input.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  input.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
  await new Promise((resolve) => setTimeout(resolve, 30));
  assert.equal(sent.length, 1);
  assert.equal(sent[0].records[0].answer, 'edited@example.com');
  input.value = 'final@example.com';
  input.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  await session.flush();
  assert.equal(sent.at(-1).records[0].answer, 'final@example.com');
  session.dispose();
  dom.window.close();
});

test('final native submit snapshots an activated application without preventing submission', async () => {
  const dom = new JSDOM('<form aria-label="Job application"><label>Email<input id="email" type="email"></label><button type="submit">Submit application</button></form>', { url: 'https://example.com/apply' });
  const document = dom.window.document;
  const snapshots = [];
  const session = createLearningSession(document, {
    capture: () => collectAnswerRecords(document),
    send: async () => ({ ok: true }),
    onFinalSubmit: (snapshot) => snapshots.push(snapshot),
  });
  const input = document.querySelector('input');
  input.value = 'final@example.com';
  input.dispatchEvent(new dom.window.Event('input', { bubbles: true }));
  session.activate('run-final');
  const submit = new dom.window.Event('submit', { bubbles: true, cancelable: true });

  const allowed = document.querySelector('form').dispatchEvent(submit);

  assert.equal(allowed, true);
  assert.equal(submit.defaultPrevented, false);
  assert.equal(snapshots.length, 1);
  assert.equal(snapshots[0].applicationId, 'run-final');
  assert.equal(snapshots[0].records[0].key, 'email');
  assert.equal(snapshots[0].records[0].answer, 'final@example.com');
  session.dispose();
  dom.window.close();
});

test('learning does not confirm values generated by autofill', async () => {
  const dom = new JSDOM('<label>Email<input id="email" type="email"></label>', { url: 'https://example.com/apply' });
  const document = dom.window.document;
  const sent = [];
  const session = createLearningSession(document, { capture: () => collectAnswerRecords(document), send: async (message) => { sent.push(message); return { ok: true }; }, delayMs: 10 });
  session.activate('run');
  await applyDecisions(document, planDeterministicFill(collectFieldDescriptors(document), [{ key: 'email', answer: 'generated@example.com', sensitivity: 'safe' }]));
  await session.flush();
  assert.equal(sent.length, 0);
  session.dispose();
  dom.window.close();
});

test('conflicting corrections retain confirmed values and sensitive facts await review', () => {
  const records = mergeLearnedAnswers([{ key: 'email', question: 'Email', answer: 'old@example.com', provenance: 'user' }], [
    { key: 'email', question: 'Email', answer: 'new@example.com', provenance: 'user' },
    { key: 'salary', question: 'Expected salary', answer: '100000', provenance: 'user' },
    { key: 'first_name', question: 'First name', answer: 'Ada', provenance: 'autofill' },
  ]);
  assert.equal(records.find((record) => record.key === 'email').answer, 'old@example.com');
  assert.equal(records.find((record) => record.key === 'email').pendingAnswer, 'new@example.com');
  assert.equal(records.find((record) => record.key === 'salary').confirmationState, 'pending');
  assert.equal(records.some((record) => record.key === 'first_name'), false);
});
